name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-static-i18n mkdocs-material mkdocs[i18n] mkdocs-git-authors-plugin mkdocs-git-revision-date-localized-plugin
      - run: mkdocs gh-deploy --force
